-- Create the Users Table
CREATE TABLE Users (
    UserID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR2(50) NOT NULL UNIQUE,
    Email VARCHAR2(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR2(255) NOT NULL,
    ProfileImage VARCHAR2(255) DEFAULT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create the UserFiles Table
CREATE TABLE UserFiles (
    FileID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID NUMBER NOT NULL,

    -- Display Info
    FileName VARCHAR2(255) NOT NULL,
    FileSizeBytes NUMBER(19) NOT NULL, -- BIGINT equivalent
    FileType VARCHAR2(50),

    -- Cloud Storage Reference
    StoragePath VARCHAR2(500) NOT NULL,
    StorageProvider VARCHAR2(50) DEFAULT 'supabase',

    -- Crypto Metadata
    EncryptionSalt VARCHAR2(255) NOT NULL,
    EncryptionIV VARCHAR2(255) NOT NULL,

    UploadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user 
        FOREIGN KEY (UserID) 
        REFERENCES Users(UserID)
);