-- Create the Users Table
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    profile_image VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create the UserFiles Table
CREATE TABLE user_files (
    file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,

    -- Display Info
    file_name VARCHAR(255) NOT NULL,
    file_size_bytes BIGINT NOT NULL, 
    file_type VARCHAR(50),

    -- Cloud Storage Reference
    storage_path VARCHAR(500) NOT NULL,
    storage_provider VARCHAR(50) DEFAULT 'supabase',

    -- Crypto Metadata
    encryption_salt VARCHAR(255) NOT NULL,
    encryption_iv VARCHAR(255) NOT NULL,

    upload_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user 
        FOREIGN KEY (user_id) 
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

